title: Yunus Emre Durak
email: yunusemre.durak@icloud.com
description: Software Engineer | Cyber Security Researcher
baseurl: ""
url: "https://r00twr3nch.github.io"
twitter_username: kullaniciadi
github_username: kullaniciadi

# Markdown AyarÄ±
markdown: kramdown
permalink: /blog/:title/